/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 列出全部服务账号及其状态 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AccountList"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts/{id}/connect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 调网关 connect，账号 idle / disconnected → online */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AccountRead"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts/{id}/transition": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 操作员手动标记账号状态（expectedFrom 做 CAS） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        expectedFrom: components["schemas"]["AccountStatusInput"];
                        to: components["schemas"]["AccountStatusInput"];
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AccountTransitionResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 最近动态：WS 事件（白名单类型）按 seq 倒序，游标分页；首屏用它，之后靠 WS 追加 */
        get: {
            parameters: {
                query?: {
                    before?: string;
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ActivityPage"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agent-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 全部群的 agent run 列表：可按状态、群筛选，按创建时间倒序游标分页（不含 steps） */
        get: {
            parameters: {
                query?: {
                    status?: components["schemas"]["AgentRunStatusInput"];
                    groupId?: string;
                    before?: string;
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AgentRunPage"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agent-runs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 某次 agent run 的详情：状态、结束原因、summary 与全部步骤（含协议错误步） */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AgentRunDetail"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 用户名密码登录，签发 access token；refresh token 只进 HttpOnly cookie */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        password: string;
                        username: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LoginResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 登出：整个会话族作废，同一 access token 立即失效，清 refresh cookie（access token 过期时凭 cookie） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LogoutResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 用 HttpOnly cookie 里的 refresh token 换新 access token（轮换；旧 token 复用则整个会话作废） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LoginResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 工作台概览：账号 / 群 / 今日消息 / Agent 运行 / 序列 / job / 待处理异常的计数（今日按 timeZone 参数的自然日，默认 UTC） */
        get: {
            parameters: {
                query?: {
                    timeZone?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DashboardSummary"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 列出全部群（含成员与进行中的运行） */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GroupList"];
                    };
                };
            };
        };
        put?: never;
        /** 建群 + 拉人 + 提升 memberAccountIds[0] 为管理员（异步 job，202） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        creatorAccountId: string;
                        memberAccountIds: string[];
                    };
                };
            };
            responses: {
                /** @description Default Response */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CreateGroupResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/groups/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 群详情：成员、开关、进行中的运行 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GroupRead"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 改群开关 agentEnabled / autoKickEnabled */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        agentEnabled?: boolean;
                        autoKickEnabled?: boolean;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GroupRead"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/groups/{id}/agent-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 某群最近的 agent run 列表（最新在前，不含 steps） */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AgentRunListResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/groups/{id}/leave-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 群里所有服务账号退群：非群主先、群主最后（异步 job，202） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LeaveAllResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/groups/{id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 群消息时间线：按 sentAt 倒序，游标分页（before = 上一页的 nextCursor） */
        get: {
            parameters: {
                query?: {
                    before?: string;
                    limit?: number;
                };
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MessagePage"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/groups/{id}/messages/{msgId}/media": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 取一条消息已下载到本地的附件文件（题目 C1） */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                    msgId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/groups/{id}/send": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 以某服务账号身份往群里发一条消息（入队，202） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        accountId: string;
                        text: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SendResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/groups/{id}/sequence-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 在某群启动一次序列运行（预检取值链；同群至多一个 running；201 后由 worker 按排期发送） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        sequenceId: string;
                        /** @default {} */
                        stepVars?: {
                            [key: string]: {
                                [key: string]: string;
                            };
                        };
                        /** @default {} */
                        vars?: {
                            [key: string]: string;
                        };
                    };
                };
            };
            responses: {
                /** @description Default Response */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SequenceRunStarted"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/groups/{id}/simulate-inbound": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 演示用：以外部成员身份往群里推一条消息（经网关模拟器，随后照常进入时间线并可触发 Agent） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        media?: {
                            base64: string;
                            contentType: components["schemas"]["SimulateMediaTypeInput"];
                        };
                        senderPlatformUserId: string;
                        text: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SimulateInboundResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 健康检查 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HealthRead"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 就绪检查：数据库可查、迁移状态与代码一致、后台 worker 在跳心跳；不就绪 503 NOT_READY */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReadinessRead"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/inconsistencies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 异常中心列表：不一致记录按创建时间倒序，可按是否已处理筛选，游标分页（不含 payload） */
        get: {
            parameters: {
                query?: {
                    resolved?: components["schemas"]["InconsistencyResolvedFilterInput"];
                    before?: string;
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["InconsistencyPage"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/inconsistencies/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 某条不一致记录的详情（含 payload 原文） */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["InconsistencyDetail"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/inconsistencies/{id}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 把一条不一致记录标记为已处理（记录处理人；幂等，重复标记返回原记录） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["InconsistencyRead"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{jobId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查异步任务（建群 / leave-all）的状态与失败步骤 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    jobId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["JobRead"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/llm/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 用给定的服务商与 key 获取可用的模型列表（Claude：Models API；Gemini：支持 generateContent 的模型） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LlmModelsRequestInput"];
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LlmModelListResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/llm/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 当前的 LLM 设置（服务商 Claude / Gemini、模型、key 提示）；Agent 服务不是 llm-agent 时 supported=false */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LlmSettingsRead"];
                    };
                };
            };
        };
        /** 保存 LLM 设置（apiKey 省略时仅在服务商不变时沿用已保存的 key），llm-agent 立即生效 */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LlmSettingsUpdateInput"];
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LlmSettingsRead"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/llm/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 用已保存的 LLM 设置测试连接（一轮带工具历史的对话 + 一次审计），失败也返回 200 与原因 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LlmTestResult"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sequence-runs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 某次序列运行的状态与每步的取值 / 排期 / 发送结果 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SequenceRunRead"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sequences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 列出全部序列定义（按创建顺序） */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SequenceList"];
                    };
                };
            };
        };
        put?: never;
        /** 创建序列定义（题目 B1 的 JSON） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SequenceDefinitionInput"];
                };
            };
            responses: {
                /** @description Default Response */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SequenceCreated"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sim-controls": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 演示用模拟控制是否打开（SIM_CONTROLS_ENABLED） */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SimControlsRead"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AccountList: components["schemas"]["AccountRead"][];
        AccountListInput: components["schemas"]["AccountReadInput"][];
        AccountRead: {
            id: string;
            platformUserId: string | null;
            rateLimitedUntil: string | null;
            status: components["schemas"]["AccountStatus"];
        };
        AccountReadInput: {
            id: string;
            platformUserId: string | null;
            rateLimitedUntil: string | null;
            status: components["schemas"]["AccountStatusInput"];
        };
        /** @enum {string} */
        AccountStatus: "idle" | "online" | "rate_limited" | "disconnected" | "suspended" | "session_expired";
        /** @enum {string} */
        AccountStatusInput: "idle" | "online" | "rate_limited" | "disconnected" | "suspended" | "session_expired";
        AccountTransitionResponse: {
            changed: boolean;
            from: components["schemas"]["AccountStatus"];
            id: string;
            membersRemovedCount: number;
            messagesCancelledCount: number;
            platformUserId: string | null;
            rateLimitedUntil: string | null;
            status: components["schemas"]["AccountStatus"];
            stepsSkippedCount: number;
        };
        AccountTransitionResponseInput: {
            changed: boolean;
            from: components["schemas"]["AccountStatusInput"];
            id: string;
            membersRemovedCount: number;
            messagesCancelledCount: number;
            platformUserId: string | null;
            rateLimitedUntil: string | null;
            status: components["schemas"]["AccountStatusInput"];
            stepsSkippedCount: number;
        };
        /** @enum {string} */
        ActivityEventType: "account_status_changed" | "account_terminal" | "inconsistency" | "message" | "agent_run" | "sequence_run" | "job" | "group_status_changed" | "group_settings_changed" | "member_changed";
        /** @enum {string} */
        ActivityEventTypeInput: "account_status_changed" | "account_terminal" | "inconsistency" | "message" | "agent_run" | "sequence_run" | "job" | "group_status_changed" | "group_settings_changed" | "member_changed";
        ActivityItem: {
            /** Format: date-time */
            createdAt: string;
            payload: {
                [key: string]: unknown;
            };
            seq: number;
            type: components["schemas"]["ActivityEventType"];
        };
        ActivityItemInput: {
            /** Format: date-time */
            createdAt: string;
            payload: {
                [key: string]: unknown;
            };
            seq: number;
            type: components["schemas"]["ActivityEventTypeInput"];
        };
        ActivityPage: {
            items: components["schemas"]["ActivityItem"][];
            nextCursor: string | null;
        };
        ActivityPageInput: {
            items: components["schemas"]["ActivityItemInput"][];
            nextCursor: string | null;
        };
        AgentRunDetail: {
            accumulatedMs: number;
            budgetMs: number;
            /** Format: date-time */
            createdAt: string;
            endReason: components["schemas"]["AgentRunEndReason"] | null;
            finishedAt: string | null;
            groupId: string;
            id: string;
            maxSteps: number;
            status: components["schemas"]["AgentRunStatus"];
            stepCount: number;
            steps: components["schemas"]["AgentStepRead"][];
            summary: string | null;
            triggerMessages: components["schemas"]["AgentTriggerMessage"][];
        };
        AgentRunDetailInput: {
            accumulatedMs: number;
            budgetMs: number;
            /** Format: date-time */
            createdAt: string;
            endReason: components["schemas"]["AgentRunEndReasonInput"] | null;
            finishedAt: string | null;
            groupId: string;
            id: string;
            maxSteps: number;
            status: components["schemas"]["AgentRunStatusInput"];
            stepCount: number;
            steps: components["schemas"]["AgentStepReadInput"][];
            summary: string | null;
            triggerMessages: components["schemas"]["AgentTriggerMessageInput"][];
        };
        /** @enum {string} */
        AgentRunEndReason: "final" | "budget_exhausted" | "wall_clock" | "protocol_errors" | "audit_blocked" | "cancelled";
        /** @enum {string} */
        AgentRunEndReasonInput: "final" | "budget_exhausted" | "wall_clock" | "protocol_errors" | "audit_blocked" | "cancelled";
        AgentRunListItem: {
            /** Format: date-time */
            createdAt: string;
            endReason: components["schemas"]["AgentRunEndReason"] | null;
            finishedAt: string | null;
            gatewayGroupId: string | null;
            groupId: string;
            id: string;
            status: components["schemas"]["AgentRunStatus"];
            stepCount: number;
            summary: string | null;
        };
        AgentRunListItemInput: {
            /** Format: date-time */
            createdAt: string;
            endReason: components["schemas"]["AgentRunEndReasonInput"] | null;
            finishedAt: string | null;
            gatewayGroupId: string | null;
            groupId: string;
            id: string;
            status: components["schemas"]["AgentRunStatusInput"];
            stepCount: number;
            summary: string | null;
        };
        AgentRunListResponse: {
            items: components["schemas"]["AgentRunRead"][];
            total: number;
        };
        AgentRunListResponseInput: {
            items: components["schemas"]["AgentRunReadInput"][];
            total: number;
        };
        AgentRunPage: {
            items: components["schemas"]["AgentRunListItem"][];
            nextCursor: string | null;
        };
        AgentRunPageInput: {
            items: components["schemas"]["AgentRunListItemInput"][];
            nextCursor: string | null;
        };
        AgentRunRead: {
            accumulatedMs: number;
            budgetMs: number;
            /** Format: date-time */
            createdAt: string;
            endReason: components["schemas"]["AgentRunEndReason"] | null;
            finishedAt: string | null;
            groupId: string;
            id: string;
            maxSteps: number;
            status: components["schemas"]["AgentRunStatus"];
            stepCount: number;
            summary: string | null;
            triggerMessages: components["schemas"]["AgentTriggerMessage"][];
        };
        AgentRunReadInput: {
            accumulatedMs: number;
            budgetMs: number;
            /** Format: date-time */
            createdAt: string;
            endReason: components["schemas"]["AgentRunEndReasonInput"] | null;
            finishedAt: string | null;
            groupId: string;
            id: string;
            maxSteps: number;
            status: components["schemas"]["AgentRunStatusInput"];
            stepCount: number;
            summary: string | null;
            triggerMessages: components["schemas"]["AgentTriggerMessageInput"][];
        };
        /** @enum {string} */
        AgentRunStatus: "running" | "finished" | "failed" | "blocked" | "cancelled";
        /** @enum {string} */
        AgentRunStatusInput: "running" | "finished" | "failed" | "blocked" | "cancelled";
        /** @enum {string} */
        AgentStepKind: "tool_use" | "final" | "protocol_error";
        /** @enum {string} */
        AgentStepKindInput: "tool_use" | "final" | "protocol_error";
        AgentStepRead: {
            auditAttempts: number;
            auditVerdict: components["schemas"]["AuditVerdict"] | null;
            completedAt: string | null;
            /** Format: date-time */
            createdAt: string;
            errorCode: string | null;
            index: number;
            input: {
                [key: string]: unknown;
            } | null;
            isError: boolean;
            kind: components["schemas"]["AgentStepKind"];
            name: string | null;
            rawResponse: string | null;
            resultSummary: string | null;
            toolUseId: string | null;
        };
        AgentStepReadInput: {
            auditAttempts: number;
            auditVerdict: components["schemas"]["AuditVerdictInput"] | null;
            completedAt: string | null;
            /** Format: date-time */
            createdAt: string;
            errorCode: string | null;
            index: number;
            input: {
                [key: string]: unknown;
            } | null;
            isError: boolean;
            kind: components["schemas"]["AgentStepKindInput"];
            name: string | null;
            rawResponse: string | null;
            resultSummary: string | null;
            toolUseId: string | null;
        };
        AgentTriggerMessage: {
            msgId: string;
            senderPlatformUserId: string;
            sentAt: string;
            text: string;
        };
        AgentTriggerMessageInput: {
            msgId: string;
            senderPlatformUserId: string;
            sentAt: string;
            text: string;
        };
        /** @enum {string} */
        AuditVerdict: "pass" | "fail";
        /** @enum {string} */
        AuditVerdictInput: "pass" | "fail";
        CreateGroupResponse: {
            jobId: string;
        };
        CreateGroupResponseInput: {
            jobId: string;
        };
        DashboardAccounts: {
            disconnected: number;
            idle: number;
            online: number;
            rate_limited: number;
            session_expired: number;
            suspended: number;
            total: number;
        };
        DashboardAccountsInput: {
            disconnected: number;
            idle: number;
            online: number;
            rate_limited: number;
            session_expired: number;
            suspended: number;
            total: number;
        };
        DashboardAgentRuns: {
            blocked: number;
            running: number;
            todayFailed: number;
            todayFinished: number;
        };
        DashboardAgentRunsInput: {
            blocked: number;
            running: number;
            todayFailed: number;
            todayFinished: number;
        };
        DashboardGroups: {
            active: number;
            agentEnabled: number;
            left: number;
            total: number;
            unreachable: number;
        };
        DashboardGroupsInput: {
            active: number;
            agentEnabled: number;
            left: number;
            total: number;
            unreachable: number;
        };
        DashboardInconsistencies: {
            unresolved: number;
        };
        DashboardInconsistenciesInput: {
            unresolved: number;
        };
        DashboardJobs: {
            running: number;
            todayFailed: number;
        };
        DashboardJobsInput: {
            running: number;
            todayFailed: number;
        };
        DashboardMessages: {
            outboundFailed: number;
            outboundQueued: number;
            outboundUnknown: number;
            todayInbound: number;
            todayOutbound: number;
        };
        DashboardMessagesInput: {
            outboundFailed: number;
            outboundQueued: number;
            outboundUnknown: number;
            todayInbound: number;
            todayOutbound: number;
        };
        DashboardSequenceRuns: {
            running: number;
        };
        DashboardSequenceRunsInput: {
            running: number;
        };
        DashboardSummary: {
            accounts: components["schemas"]["DashboardAccounts"];
            agentRuns: components["schemas"]["DashboardAgentRuns"];
            /** Format: date-time */
            dayStart: string;
            /** Format: date-time */
            generatedAt: string;
            groups: components["schemas"]["DashboardGroups"];
            inconsistencies: components["schemas"]["DashboardInconsistencies"];
            jobs: components["schemas"]["DashboardJobs"];
            messages: components["schemas"]["DashboardMessages"];
            sequenceRuns: components["schemas"]["DashboardSequenceRuns"];
            timeZone: string;
        };
        DashboardSummaryInput: {
            accounts: components["schemas"]["DashboardAccountsInput"];
            agentRuns: components["schemas"]["DashboardAgentRunsInput"];
            /** Format: date-time */
            dayStart: string;
            /** Format: date-time */
            generatedAt: string;
            groups: components["schemas"]["DashboardGroupsInput"];
            inconsistencies: components["schemas"]["DashboardInconsistenciesInput"];
            jobs: components["schemas"]["DashboardJobsInput"];
            messages: components["schemas"]["DashboardMessagesInput"];
            sequenceRuns: components["schemas"]["DashboardSequenceRunsInput"];
            timeZone: string;
        };
        /** @enum {string} */
        DeliveryStatus: "queued" | "accepted" | "sent" | "failed" | "unknown" | "cancelled";
        /** @enum {string} */
        DeliveryStatusInput: "queued" | "accepted" | "sent" | "failed" | "unknown" | "cancelled";
        GroupList: components["schemas"]["GroupRead"][];
        GroupListInput: components["schemas"]["GroupReadInput"][];
        GroupMemberRead: {
            accountId: string | null;
            platformUserId: string;
            role: components["schemas"]["MemberRole"];
        };
        GroupMemberReadInput: {
            accountId: string | null;
            platformUserId: string;
            role: components["schemas"]["MemberRoleInput"];
        };
        GroupRead: {
            activeAgentRunId: string | null;
            activeSequenceRunId: string | null;
            agentEnabled: boolean;
            autoKickEnabled: boolean;
            creatorAccountId: string;
            gatewayGroupId: string | null;
            id: string;
            members: components["schemas"]["GroupMemberRead"][];
            status: components["schemas"]["GroupStatus"];
        };
        GroupReadInput: {
            activeAgentRunId: string | null;
            activeSequenceRunId: string | null;
            agentEnabled: boolean;
            autoKickEnabled: boolean;
            creatorAccountId: string;
            gatewayGroupId: string | null;
            id: string;
            members: components["schemas"]["GroupMemberReadInput"][];
            status: components["schemas"]["GroupStatusInput"];
        };
        /** @enum {string} */
        GroupStatus: "active" | "unreachable" | "left";
        /** @enum {string} */
        GroupStatusInput: "active" | "unreachable" | "left";
        HealthRead: {
            /** @constant */
            ok: true;
            schemaVersion: string;
        };
        HealthReadInput: {
            /** @constant */
            ok: true;
            schemaVersion: string;
        };
        InconsistencyDetail: {
            /** Format: date-time */
            createdAt: string;
            id: string;
            kind: string;
            message: string;
            payload: {
                [key: string]: unknown;
            } | null;
            ref: string | null;
            resolvedAt: string | null;
            resolvedBy: string | null;
        };
        InconsistencyDetailInput: {
            /** Format: date-time */
            createdAt: string;
            id: string;
            kind: string;
            message: string;
            payload: {
                [key: string]: unknown;
            } | null;
            ref: string | null;
            resolvedAt: string | null;
            resolvedBy: string | null;
        };
        InconsistencyPage: {
            items: components["schemas"]["InconsistencyRead"][];
            nextCursor: string | null;
        };
        InconsistencyPageInput: {
            items: components["schemas"]["InconsistencyReadInput"][];
            nextCursor: string | null;
        };
        InconsistencyRead: {
            /** Format: date-time */
            createdAt: string;
            id: string;
            kind: string;
            message: string;
            ref: string | null;
            resolvedAt: string | null;
            resolvedBy: string | null;
        };
        InconsistencyReadInput: {
            /** Format: date-time */
            createdAt: string;
            id: string;
            kind: string;
            message: string;
            ref: string | null;
            resolvedAt: string | null;
            resolvedBy: string | null;
        };
        /** @enum {string} */
        InconsistencyResolvedFilter: "true" | "false";
        /** @enum {string} */
        InconsistencyResolvedFilterInput: "true" | "false";
        JobErrorRead: {
            accountId: string | null;
            code: string;
            message: string | null;
            step: string;
            stepKind: components["schemas"]["JobStepKind"];
        };
        JobErrorReadInput: {
            accountId: string | null;
            code: string;
            message: string | null;
            step: string;
            stepKind: components["schemas"]["JobStepKindInput"];
        };
        /** @enum {string} */
        JobKind: "create_group" | "leave_all";
        /** @enum {string} */
        JobKindInput: "create_group" | "leave_all";
        JobRead: {
            /** Format: date-time */
            createdAt: string;
            errors: components["schemas"]["JobErrorRead"][];
            finishedAt: string | null;
            groupId: string | null;
            id: string;
            kind: components["schemas"]["JobKind"];
            status: components["schemas"]["JobStatus"];
            step: string | null;
        };
        JobReadInput: {
            /** Format: date-time */
            createdAt: string;
            errors: components["schemas"]["JobErrorReadInput"][];
            finishedAt: string | null;
            groupId: string | null;
            id: string;
            kind: components["schemas"]["JobKindInput"];
            status: components["schemas"]["JobStatusInput"];
            step: string | null;
        };
        /** @enum {string} */
        JobStatus: "running" | "finished" | "failed";
        /** @enum {string} */
        JobStatusInput: "running" | "finished" | "failed";
        /** @enum {string} */
        JobStepKind: "create" | "invite" | "join" | "promote" | "leave";
        /** @enum {string} */
        JobStepKindInput: "create" | "invite" | "join" | "promote" | "leave";
        LeaveAllResponse: {
            jobId: string;
        };
        LeaveAllResponseInput: {
            jobId: string;
        };
        /** @enum {string} */
        LlmConfigSource: "file" | "none";
        /** @enum {string} */
        LlmConfigSourceInput: "file" | "none";
        LlmModelListResponse: {
            items: components["schemas"]["LlmModelRead"][];
            total: number;
        };
        LlmModelListResponseInput: {
            items: components["schemas"]["LlmModelReadInput"][];
            total: number;
        };
        LlmModelRead: {
            displayName: string;
            id: string;
        };
        LlmModelReadInput: {
            displayName: string;
            id: string;
        };
        LlmModelsRequest: {
            /** @description 省略时沿用已保存的 key —— 仅当 provider 与已保存的相同 */
            apiKey?: string;
            provider: components["schemas"]["LlmProvider"];
        };
        LlmModelsRequestInput: {
            /** @description 省略时沿用已保存的 key —— 仅当 provider 与已保存的相同 */
            apiKey?: string;
            provider: components["schemas"]["LlmProviderInput"];
        };
        /** @enum {string} */
        LlmProvider: "anthropic" | "gemini";
        /** @enum {string} */
        LlmProviderInput: "anthropic" | "gemini";
        LlmSettingsRead: {
            apiKeyHint: string | null;
            auditModel: string | null;
            hasApiKey: boolean;
            model: string | null;
            provider: components["schemas"]["LlmProvider"] | null;
            source: components["schemas"]["LlmConfigSource"] | null;
            supported: boolean;
            updatedAt: string | null;
        };
        LlmSettingsReadInput: {
            apiKeyHint: string | null;
            auditModel: string | null;
            hasApiKey: boolean;
            model: string | null;
            provider: components["schemas"]["LlmProviderInput"] | null;
            source: components["schemas"]["LlmConfigSourceInput"] | null;
            supported: boolean;
            updatedAt: string | null;
        };
        LlmSettingsUpdate: {
            /** @description 省略时沿用已保存的 key —— 仅当 provider 与已保存的相同 */
            apiKey?: string;
            auditModel?: string | null;
            model: string;
            provider: components["schemas"]["LlmProvider"];
        };
        LlmSettingsUpdateInput: {
            /** @description 省略时沿用已保存的 key —— 仅当 provider 与已保存的相同 */
            apiKey?: string;
            auditModel?: string | null;
            model: string;
            provider: components["schemas"]["LlmProviderInput"];
        };
        LlmTestResult: {
            latencyMs: number;
            message: string;
            model: string | null;
            ok: boolean;
        };
        LlmTestResultInput: {
            latencyMs: number;
            message: string;
            model: string | null;
            ok: boolean;
        };
        LoginResponse: {
            accessToken: string;
        };
        LoginResponseInput: {
            accessToken: string;
        };
        LogoutResponse: {
            /** @constant */
            ok: true;
        };
        LogoutResponseInput: {
            /** @constant */
            ok: true;
        };
        /** @enum {string} */
        MediaStatus: "downloading" | "ready" | "expired" | "failed" | "purged";
        /** @enum {string} */
        MediaStatusInput: "downloading" | "ready" | "expired" | "failed" | "purged";
        /** @enum {string} */
        MemberRole: "creator" | "admin" | "member";
        /** @enum {string} */
        MemberRoleInput: "creator" | "admin" | "member";
        MessagePage: {
            items: components["schemas"]["MessageRead"][];
            nextCursor: string | null;
        };
        MessagePageInput: {
            items: components["schemas"]["MessageReadInput"][];
            nextCursor: string | null;
        };
        MessageRead: {
            clientMsgId: string | null;
            deliveryStatus: components["schemas"]["DeliveryStatus"] | null;
            failCode: string | null;
            isOwn: boolean;
            localFilePath: string | null;
            mediaStatus: components["schemas"]["MediaStatus"] | null;
            mediaUrl: string | null;
            msgId: string | null;
            senderPlatformUserId: string;
            /** Format: date-time */
            sentAt: string;
            text: string;
        };
        MessageReadInput: {
            clientMsgId: string | null;
            deliveryStatus: components["schemas"]["DeliveryStatusInput"] | null;
            failCode: string | null;
            isOwn: boolean;
            localFilePath: string | null;
            mediaStatus: components["schemas"]["MediaStatusInput"] | null;
            mediaUrl: string | null;
            msgId: string | null;
            senderPlatformUserId: string;
            /** Format: date-time */
            sentAt: string;
            text: string;
        };
        /** @enum {string} */
        ReadinessCheckState: "ok" | "fail";
        /** @enum {string} */
        ReadinessCheckStateInput: "ok" | "fail";
        ReadinessRead: {
            checks: {
                database: components["schemas"]["ReadinessCheckState"];
                scheduler: components["schemas"]["ReadinessCheckState"];
                schema: components["schemas"]["ReadinessCheckState"];
            };
            /** @constant */
            ok: true;
        };
        ReadinessReadInput: {
            checks: {
                database: components["schemas"]["ReadinessCheckStateInput"];
                scheduler: components["schemas"]["ReadinessCheckStateInput"];
                schema: components["schemas"]["ReadinessCheckStateInput"];
            };
            /** @constant */
            ok: true;
        };
        SendResponse: {
            clientMsgId: string;
        };
        SendResponseInput: {
            clientMsgId: string;
        };
        /** @enum {string} */
        SequenceAccountRole: "admin" | "member";
        /** @enum {string} */
        SequenceAccountRoleInput: "admin" | "member";
        SequenceCreated: {
            id: string;
        };
        SequenceCreatedInput: {
            id: string;
        };
        SequenceDefinition: {
            name: string;
            steps: components["schemas"]["SequenceStepDefinition"][];
        };
        SequenceDefinitionInput: {
            name: string;
            steps: components["schemas"]["SequenceStepDefinitionInput"][];
        };
        SequenceList: {
            items: components["schemas"]["SequenceRead"][];
            total: number;
        };
        SequenceListInput: {
            items: components["schemas"]["SequenceReadInput"][];
            total: number;
        };
        SequenceRead: {
            /** Format: date-time */
            createdAt: string;
            id: string;
            name: string;
            steps: components["schemas"]["SequenceStepDefinition"][];
        };
        SequenceReadInput: {
            /** Format: date-time */
            createdAt: string;
            id: string;
            name: string;
            steps: components["schemas"]["SequenceStepDefinitionInput"][];
        };
        SequenceRunRead: {
            /** Format: date-time */
            createdAt: string;
            currentStepIndex: number;
            finishedAt: string | null;
            groupId: string;
            id: string;
            sequenceId: string;
            status: components["schemas"]["SequenceRunStatus"];
            steps: components["schemas"]["SequenceRunStepRead"][];
        };
        SequenceRunReadInput: {
            /** Format: date-time */
            createdAt: string;
            currentStepIndex: number;
            finishedAt: string | null;
            groupId: string;
            id: string;
            sequenceId: string;
            status: components["schemas"]["SequenceRunStatusInput"];
            steps: components["schemas"]["SequenceRunStepReadInput"][];
        };
        SequenceRunStarted: {
            runId: string;
        };
        SequenceRunStartedInput: {
            runId: string;
        };
        /** @enum {string} */
        SequenceRunStatus: "running" | "finished" | "failed" | "stopped";
        /** @enum {string} */
        SequenceRunStatusInput: "running" | "finished" | "failed" | "stopped";
        SequenceRunStepRead: {
            accountId: string | null;
            accountRole: components["schemas"]["SequenceAccountRole"];
            clientMsgId: string | null;
            delaySeconds: number;
            failCode: string | null;
            index: number;
            resolvedVars: {
                [key: string]: string;
            };
            scheduledAt: string | null;
            sentAt: string | null;
            skippedAt: string | null;
            status: components["schemas"]["SequenceStepStatus"];
            varSources: {
                [key: string]: string;
            };
        };
        SequenceRunStepReadInput: {
            accountId: string | null;
            accountRole: components["schemas"]["SequenceAccountRoleInput"];
            clientMsgId: string | null;
            delaySeconds: number;
            failCode: string | null;
            index: number;
            resolvedVars: {
                [key: string]: string;
            };
            scheduledAt: string | null;
            sentAt: string | null;
            skippedAt: string | null;
            status: components["schemas"]["SequenceStepStatusInput"];
            varSources: {
                [key: string]: string;
            };
        };
        SequenceStepDefinition: {
            accountRole: components["schemas"]["SequenceAccountRole"];
            delaySeconds: number;
            index: number;
            text: string;
        };
        SequenceStepDefinitionInput: {
            accountRole: components["schemas"]["SequenceAccountRoleInput"];
            delaySeconds: number;
            index: number;
            text: string;
        };
        /** @enum {string} */
        SequenceStepStatus: "pending" | "accepted" | "sent" | "skipped" | "failed";
        /** @enum {string} */
        SequenceStepStatusInput: "pending" | "accepted" | "sent" | "skipped" | "failed";
        SimControlsRead: {
            enabled: boolean;
        };
        SimControlsReadInput: {
            enabled: boolean;
        };
        SimulateInboundResponse: {
            gatewayGroupId: string;
        };
        SimulateInboundResponseInput: {
            gatewayGroupId: string;
        };
        /** @enum {string} */
        SimulateMediaType: "image/png" | "image/jpeg" | "image/gif" | "image/webp";
        /** @enum {string} */
        SimulateMediaTypeInput: "image/png" | "image/jpeg" | "image/gif" | "image/webp";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
