/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 列出全部服务账号及其状态 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AccountList"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts/{id}/connect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 调网关 connect，账号 idle / disconnected → online */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AccountRead"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts/{id}/transition": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 操作员手动标记账号状态（expectedFrom 做 CAS） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        expectedFrom: components["schemas"]["AccountStatusInput"];
                        to: components["schemas"]["AccountStatusInput"];
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AccountTransitionResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agent-runs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 某次 agent run 的详情：状态、结束原因、summary 与全部步骤（含协议错误步） */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AgentRunDetail"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 用户名密码登录，签发 access token；refresh token 只进 HttpOnly cookie */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        password: string;
                        username: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LoginResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 登出：整个会话族作废，同一 access token 立即失效，清 refresh cookie */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LogoutResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 用 HttpOnly cookie 里的 refresh token 换新 access token（轮换；旧 token 复用则整个会话作废） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LoginResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 列出全部群（含成员与进行中的运行） */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GroupList"];
                    };
                };
            };
        };
        put?: never;
        /** 建群 + 拉人 + 提升 memberAccountIds[0] 为管理员（异步 job，202） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        creatorAccountId: string;
                        memberAccountIds: string[];
                    };
                };
            };
            responses: {
                /** @description Default Response */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CreateGroupResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/groups/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 群详情：成员、开关、进行中的运行 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GroupRead"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 改群开关 agentEnabled / autoKickEnabled */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        agentEnabled?: boolean;
                        autoKickEnabled?: boolean;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GroupRead"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/groups/{id}/agent-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 某群最近的 agent run 列表（最新在前，不含 steps） */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AgentRunListResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/groups/{id}/leave-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 群里所有服务账号退群：非群主先、群主最后（异步 job，202） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LeaveAllResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/groups/{id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 群消息时间线：按 sentAt 倒序，游标分页（before = 上一页的 nextCursor） */
        get: {
            parameters: {
                query?: {
                    before?: string;
                    limit?: number;
                };
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MessagePage"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/groups/{id}/send": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 以某服务账号身份往群里发一条消息（入队，202） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        accountId: string;
                        text: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SendResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/groups/{id}/sequence-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 在某群启动一次序列运行（预检取值链；同群至多一个 running；201 后由 worker 按排期发送） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        sequenceId: string;
                        /** @default {} */
                        stepVars?: {
                            [key: string]: {
                                [key: string]: string;
                            };
                        };
                        /** @default {} */
                        vars?: {
                            [key: string]: string;
                        };
                    };
                };
            };
            responses: {
                /** @description Default Response */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SequenceRunStarted"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 健康检查 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HealthRead"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{jobId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查异步任务（建群 / leave-all）的状态与失败步骤 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    jobId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["JobRead"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/llm/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 用给定的 Base URL 与 key 向服务商获取模型列表（按 id 排序） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LlmModelsRequestInput"];
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LlmModelListResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/llm/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 当前的 LLM 设置（Base URL、模型、key 提示）；Agent 服务不是 llm-agent 时 supported=false */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LlmSettingsRead"];
                    };
                };
            };
        };
        /** 保存 LLM 设置（apiKey 省略时仅在 Base URL 不变时沿用已保存的 key），llm-agent 立即生效 */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LlmSettingsUpdateInput"];
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LlmSettingsRead"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/llm/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 用已保存的 LLM 设置测试连接（一轮带工具历史的对话 + 一次审计），失败也返回 200 与原因 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LlmTestResult"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sequence-runs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 某次序列运行的状态与每步的取值 / 排期 / 发送结果 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SequenceRunRead"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sequences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 列出全部序列定义（按创建顺序） */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SequenceList"];
                    };
                };
            };
        };
        put?: never;
        /** 创建序列定义（题目 B1 的 JSON） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SequenceDefinitionInput"];
                };
            };
            responses: {
                /** @description Default Response */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SequenceCreated"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AccountList: components["schemas"]["AccountRead"][];
        AccountListInput: components["schemas"]["AccountReadInput"][];
        AccountRead: {
            id: string;
            platformUserId: string | null;
            rateLimitedUntil: string | null;
            status: components["schemas"]["AccountStatus"];
        };
        AccountReadInput: {
            id: string;
            platformUserId: string | null;
            rateLimitedUntil: string | null;
            status: components["schemas"]["AccountStatusInput"];
        };
        /** @enum {string} */
        AccountStatus: "idle" | "online" | "rate_limited" | "disconnected" | "suspended" | "session_expired";
        /** @enum {string} */
        AccountStatusInput: "idle" | "online" | "rate_limited" | "disconnected" | "suspended" | "session_expired";
        AccountTransitionResponse: {
            changed: boolean;
            from: components["schemas"]["AccountStatus"];
            id: string;
            membersRemovedCount: number;
            messagesCancelledCount: number;
            platformUserId: string | null;
            rateLimitedUntil: string | null;
            status: components["schemas"]["AccountStatus"];
            stepsSkippedCount: number;
        };
        AccountTransitionResponseInput: {
            changed: boolean;
            from: components["schemas"]["AccountStatusInput"];
            id: string;
            membersRemovedCount: number;
            messagesCancelledCount: number;
            platformUserId: string | null;
            rateLimitedUntil: string | null;
            status: components["schemas"]["AccountStatusInput"];
            stepsSkippedCount: number;
        };
        AgentRunDetail: {
            accumulatedMs: number;
            budgetMs: number;
            /** Format: date-time */
            createdAt: string;
            endReason: components["schemas"]["AgentRunEndReason"] | null;
            finishedAt: string | null;
            groupId: string;
            id: string;
            maxSteps: number;
            status: components["schemas"]["AgentRunStatus"];
            stepCount: number;
            steps: components["schemas"]["AgentStepRead"][];
            summary: string | null;
            triggerMessages: components["schemas"]["AgentTriggerMessage"][];
        };
        AgentRunDetailInput: {
            accumulatedMs: number;
            budgetMs: number;
            /** Format: date-time */
            createdAt: string;
            endReason: components["schemas"]["AgentRunEndReasonInput"] | null;
            finishedAt: string | null;
            groupId: string;
            id: string;
            maxSteps: number;
            status: components["schemas"]["AgentRunStatusInput"];
            stepCount: number;
            steps: components["schemas"]["AgentStepReadInput"][];
            summary: string | null;
            triggerMessages: components["schemas"]["AgentTriggerMessageInput"][];
        };
        /** @enum {string} */
        AgentRunEndReason: "final" | "budget_exhausted" | "wall_clock" | "protocol_errors" | "audit_blocked" | "cancelled";
        /** @enum {string} */
        AgentRunEndReasonInput: "final" | "budget_exhausted" | "wall_clock" | "protocol_errors" | "audit_blocked" | "cancelled";
        AgentRunListResponse: {
            items: components["schemas"]["AgentRunRead"][];
            total: number;
        };
        AgentRunListResponseInput: {
            items: components["schemas"]["AgentRunReadInput"][];
            total: number;
        };
        AgentRunRead: {
            accumulatedMs: number;
            budgetMs: number;
            /** Format: date-time */
            createdAt: string;
            endReason: components["schemas"]["AgentRunEndReason"] | null;
            finishedAt: string | null;
            groupId: string;
            id: string;
            maxSteps: number;
            status: components["schemas"]["AgentRunStatus"];
            stepCount: number;
            summary: string | null;
            triggerMessages: components["schemas"]["AgentTriggerMessage"][];
        };
        AgentRunReadInput: {
            accumulatedMs: number;
            budgetMs: number;
            /** Format: date-time */
            createdAt: string;
            endReason: components["schemas"]["AgentRunEndReasonInput"] | null;
            finishedAt: string | null;
            groupId: string;
            id: string;
            maxSteps: number;
            status: components["schemas"]["AgentRunStatusInput"];
            stepCount: number;
            summary: string | null;
            triggerMessages: components["schemas"]["AgentTriggerMessageInput"][];
        };
        /** @enum {string} */
        AgentRunStatus: "running" | "finished" | "failed" | "blocked" | "cancelled";
        /** @enum {string} */
        AgentRunStatusInput: "running" | "finished" | "failed" | "blocked" | "cancelled";
        /** @enum {string} */
        AgentStepKind: "tool_use" | "final" | "protocol_error";
        /** @enum {string} */
        AgentStepKindInput: "tool_use" | "final" | "protocol_error";
        AgentStepRead: {
            auditAttempts: number;
            auditVerdict: components["schemas"]["AuditVerdict"] | null;
            completedAt: string | null;
            /** Format: date-time */
            createdAt: string;
            errorCode: string | null;
            index: number;
            input: {
                [key: string]: unknown;
            } | null;
            isError: boolean;
            kind: components["schemas"]["AgentStepKind"];
            name: string | null;
            rawResponse: string | null;
            resultSummary: string | null;
            toolUseId: string | null;
        };
        AgentStepReadInput: {
            auditAttempts: number;
            auditVerdict: components["schemas"]["AuditVerdictInput"] | null;
            completedAt: string | null;
            /** Format: date-time */
            createdAt: string;
            errorCode: string | null;
            index: number;
            input: {
                [key: string]: unknown;
            } | null;
            isError: boolean;
            kind: components["schemas"]["AgentStepKindInput"];
            name: string | null;
            rawResponse: string | null;
            resultSummary: string | null;
            toolUseId: string | null;
        };
        AgentTriggerMessage: {
            msgId: string;
            senderPlatformUserId: string;
            sentAt: string;
            text: string;
        };
        AgentTriggerMessageInput: {
            msgId: string;
            senderPlatformUserId: string;
            sentAt: string;
            text: string;
        };
        /** @enum {string} */
        AuditVerdict: "pass" | "fail";
        /** @enum {string} */
        AuditVerdictInput: "pass" | "fail";
        CreateGroupResponse: {
            jobId: string;
        };
        CreateGroupResponseInput: {
            jobId: string;
        };
        /** @enum {string} */
        DeliveryStatus: "queued" | "accepted" | "sent" | "failed" | "unknown" | "cancelled";
        /** @enum {string} */
        DeliveryStatusInput: "queued" | "accepted" | "sent" | "failed" | "unknown" | "cancelled";
        GroupList: components["schemas"]["GroupRead"][];
        GroupListInput: components["schemas"]["GroupReadInput"][];
        GroupMemberRead: {
            accountId: string | null;
            platformUserId: string;
            role: components["schemas"]["MemberRole"];
        };
        GroupMemberReadInput: {
            accountId: string | null;
            platformUserId: string;
            role: components["schemas"]["MemberRoleInput"];
        };
        GroupRead: {
            activeAgentRunId: string | null;
            activeSequenceRunId: string | null;
            agentEnabled: boolean;
            autoKickEnabled: boolean;
            creatorAccountId: string;
            gatewayGroupId: string | null;
            id: string;
            members: components["schemas"]["GroupMemberRead"][];
            status: components["schemas"]["GroupStatus"];
        };
        GroupReadInput: {
            activeAgentRunId: string | null;
            activeSequenceRunId: string | null;
            agentEnabled: boolean;
            autoKickEnabled: boolean;
            creatorAccountId: string;
            gatewayGroupId: string | null;
            id: string;
            members: components["schemas"]["GroupMemberReadInput"][];
            status: components["schemas"]["GroupStatusInput"];
        };
        /** @enum {string} */
        GroupStatus: "active" | "unreachable" | "left";
        /** @enum {string} */
        GroupStatusInput: "active" | "unreachable" | "left";
        HealthRead: {
            /** @constant */
            ok: true;
            schemaVersion: string;
        };
        HealthReadInput: {
            /** @constant */
            ok: true;
            schemaVersion: string;
        };
        JobErrorRead: {
            accountId: string | null;
            code: string;
            message: string | null;
            step: string;
            stepKind: components["schemas"]["JobStepKind"];
        };
        JobErrorReadInput: {
            accountId: string | null;
            code: string;
            message: string | null;
            step: string;
            stepKind: components["schemas"]["JobStepKindInput"];
        };
        /** @enum {string} */
        JobKind: "create_group" | "leave_all";
        /** @enum {string} */
        JobKindInput: "create_group" | "leave_all";
        JobRead: {
            /** Format: date-time */
            createdAt: string;
            errors: components["schemas"]["JobErrorRead"][];
            finishedAt: string | null;
            groupId: string | null;
            id: string;
            kind: components["schemas"]["JobKind"];
            status: components["schemas"]["JobStatus"];
            step: string | null;
        };
        JobReadInput: {
            /** Format: date-time */
            createdAt: string;
            errors: components["schemas"]["JobErrorReadInput"][];
            finishedAt: string | null;
            groupId: string | null;
            id: string;
            kind: components["schemas"]["JobKindInput"];
            status: components["schemas"]["JobStatusInput"];
            step: string | null;
        };
        /** @enum {string} */
        JobStatus: "running" | "finished" | "failed";
        /** @enum {string} */
        JobStatusInput: "running" | "finished" | "failed";
        /** @enum {string} */
        JobStepKind: "create" | "invite" | "join" | "promote" | "leave";
        /** @enum {string} */
        JobStepKindInput: "create" | "invite" | "join" | "promote" | "leave";
        LeaveAllResponse: {
            jobId: string;
        };
        LeaveAllResponseInput: {
            jobId: string;
        };
        /** @enum {string} */
        LlmConfigSource: "file" | "none";
        /** @enum {string} */
        LlmConfigSourceInput: "file" | "none";
        LlmModelListResponse: {
            items: components["schemas"]["LlmModelRead"][];
            total: number;
        };
        LlmModelListResponseInput: {
            items: components["schemas"]["LlmModelReadInput"][];
            total: number;
        };
        LlmModelRead: {
            id: string;
            ownedBy: string | null;
        };
        LlmModelReadInput: {
            id: string;
            ownedBy: string | null;
        };
        LlmModelsRequest: {
            /** @description 省略时沿用已保存的 key —— 仅当 baseUrl 与已保存的相同 */
            apiKey?: string;
            /**
             * Format: uri
             * @description OpenAI Chat Completions 兼容端点的 base url，不含 /chat/completions
             */
            baseUrl: string;
        };
        LlmModelsRequestInput: {
            /** @description 省略时沿用已保存的 key —— 仅当 baseUrl 与已保存的相同 */
            apiKey?: string;
            /**
             * Format: uri
             * @description OpenAI Chat Completions 兼容端点的 base url，不含 /chat/completions
             */
            baseUrl: string;
        };
        LlmSettingsRead: {
            apiKeyHint: string | null;
            auditModel: string | null;
            baseUrl: string | null;
            hasApiKey: boolean;
            model: string | null;
            source: components["schemas"]["LlmConfigSource"] | null;
            supported: boolean;
            updatedAt: string | null;
        };
        LlmSettingsReadInput: {
            apiKeyHint: string | null;
            auditModel: string | null;
            baseUrl: string | null;
            hasApiKey: boolean;
            model: string | null;
            source: components["schemas"]["LlmConfigSourceInput"] | null;
            supported: boolean;
            updatedAt: string | null;
        };
        LlmSettingsUpdate: {
            /** @description 省略时沿用已保存的 key —— 仅当 baseUrl 与已保存的相同 */
            apiKey?: string;
            auditModel?: string | null;
            /**
             * Format: uri
             * @description OpenAI Chat Completions 兼容端点的 base url，不含 /chat/completions
             */
            baseUrl: string;
            model: string;
        };
        LlmSettingsUpdateInput: {
            /** @description 省略时沿用已保存的 key —— 仅当 baseUrl 与已保存的相同 */
            apiKey?: string;
            auditModel?: string | null;
            /**
             * Format: uri
             * @description OpenAI Chat Completions 兼容端点的 base url，不含 /chat/completions
             */
            baseUrl: string;
            model: string;
        };
        LlmTestResult: {
            latencyMs: number;
            message: string;
            model: string | null;
            ok: boolean;
        };
        LlmTestResultInput: {
            latencyMs: number;
            message: string;
            model: string | null;
            ok: boolean;
        };
        LoginResponse: {
            accessToken: string;
        };
        LoginResponseInput: {
            accessToken: string;
        };
        LogoutResponse: {
            /** @constant */
            ok: true;
        };
        LogoutResponseInput: {
            /** @constant */
            ok: true;
        };
        /** @enum {string} */
        MemberRole: "creator" | "admin" | "member";
        /** @enum {string} */
        MemberRoleInput: "creator" | "admin" | "member";
        MessagePage: {
            items: components["schemas"]["MessageRead"][];
            nextCursor: string | null;
        };
        MessagePageInput: {
            items: components["schemas"]["MessageReadInput"][];
            nextCursor: string | null;
        };
        MessageRead: {
            clientMsgId: string | null;
            deliveryStatus: components["schemas"]["DeliveryStatus"] | null;
            failCode: string | null;
            isOwn: boolean;
            msgId: string | null;
            senderPlatformUserId: string;
            /** Format: date-time */
            sentAt: string;
            text: string;
        };
        MessageReadInput: {
            clientMsgId: string | null;
            deliveryStatus: components["schemas"]["DeliveryStatusInput"] | null;
            failCode: string | null;
            isOwn: boolean;
            msgId: string | null;
            senderPlatformUserId: string;
            /** Format: date-time */
            sentAt: string;
            text: string;
        };
        SendResponse: {
            clientMsgId: string;
        };
        SendResponseInput: {
            clientMsgId: string;
        };
        /** @enum {string} */
        SequenceAccountRole: "admin" | "member";
        /** @enum {string} */
        SequenceAccountRoleInput: "admin" | "member";
        SequenceCreated: {
            id: string;
        };
        SequenceCreatedInput: {
            id: string;
        };
        SequenceDefinition: {
            name: string;
            steps: components["schemas"]["SequenceStepDefinition"][];
        };
        SequenceDefinitionInput: {
            name: string;
            steps: components["schemas"]["SequenceStepDefinitionInput"][];
        };
        SequenceList: {
            items: components["schemas"]["SequenceRead"][];
            total: number;
        };
        SequenceListInput: {
            items: components["schemas"]["SequenceReadInput"][];
            total: number;
        };
        SequenceRead: {
            /** Format: date-time */
            createdAt: string;
            id: string;
            name: string;
            steps: components["schemas"]["SequenceStepDefinition"][];
        };
        SequenceReadInput: {
            /** Format: date-time */
            createdAt: string;
            id: string;
            name: string;
            steps: components["schemas"]["SequenceStepDefinitionInput"][];
        };
        SequenceRunRead: {
            /** Format: date-time */
            createdAt: string;
            currentStepIndex: number;
            finishedAt: string | null;
            groupId: string;
            id: string;
            sequenceId: string;
            status: components["schemas"]["SequenceRunStatus"];
            steps: components["schemas"]["SequenceRunStepRead"][];
        };
        SequenceRunReadInput: {
            /** Format: date-time */
            createdAt: string;
            currentStepIndex: number;
            finishedAt: string | null;
            groupId: string;
            id: string;
            sequenceId: string;
            status: components["schemas"]["SequenceRunStatusInput"];
            steps: components["schemas"]["SequenceRunStepReadInput"][];
        };
        SequenceRunStarted: {
            runId: string;
        };
        SequenceRunStartedInput: {
            runId: string;
        };
        /** @enum {string} */
        SequenceRunStatus: "running" | "finished" | "failed" | "stopped";
        /** @enum {string} */
        SequenceRunStatusInput: "running" | "finished" | "failed" | "stopped";
        SequenceRunStepRead: {
            accountId: string | null;
            accountRole: components["schemas"]["SequenceAccountRole"];
            clientMsgId: string | null;
            delaySeconds: number;
            failCode: string | null;
            index: number;
            resolvedVars: {
                [key: string]: string;
            };
            scheduledAt: string | null;
            sentAt: string | null;
            skippedAt: string | null;
            status: components["schemas"]["SequenceStepStatus"];
            varSources: {
                [key: string]: string;
            };
        };
        SequenceRunStepReadInput: {
            accountId: string | null;
            accountRole: components["schemas"]["SequenceAccountRoleInput"];
            clientMsgId: string | null;
            delaySeconds: number;
            failCode: string | null;
            index: number;
            resolvedVars: {
                [key: string]: string;
            };
            scheduledAt: string | null;
            sentAt: string | null;
            skippedAt: string | null;
            status: components["schemas"]["SequenceStepStatusInput"];
            varSources: {
                [key: string]: string;
            };
        };
        SequenceStepDefinition: {
            accountRole: components["schemas"]["SequenceAccountRole"];
            delaySeconds: number;
            index: number;
            text: string;
        };
        SequenceStepDefinitionInput: {
            accountRole: components["schemas"]["SequenceAccountRoleInput"];
            delaySeconds: number;
            index: number;
            text: string;
        };
        /** @enum {string} */
        SequenceStepStatus: "pending" | "accepted" | "sent" | "skipped" | "failed";
        /** @enum {string} */
        SequenceStepStatusInput: "pending" | "accepted" | "sent" | "skipped" | "failed";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
